"""High-fidelity ingest path — engine B (§9).

Loads precomputed time series from OpenFAST / MoorDyn-with-EI / OrcaFlex (CSV or parquet),
validates columns and units, and runs the SAME §5.6 fatigue pipeline on the real signal.
Every derived figure is tagged "high-fidelity (ingested)". Engine-A and engine-B numbers
are never blended in one figure without an explicit, labelled comparison.

Two accepted input shapes (auto-detected):
  A. platform motion  — columns: time[s], surge[m], pitch[deg]  (fairlead motion is derived
     via the same quasi-static cable family as the live engine);
  B. cable response   — columns: time[s], curvature_hangoff[1/m], tension_hangoff[N]
     (stress computed directly from the equivalent-stress model, bypassing the family).
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd

from physics.cable import (QuasiStaticFamily, build_quasistatic_family,
                           region_stress_timeseries)
from physics.fatigue import FatigueParams, rainflow_damage


@dataclass
class IngestResult:
    kind: str                    # 'platform_motion' | 'cable_response'
    columns: list
    t: np.ndarray
    stress_Pa: np.ndarray        # hang-off stress
    fatigue: object              # FatigueResult
    fidelity: str = "high-fidelity (ingested)"


REQUIRED_A = {"time", "surge", "pitch"}
REQUIRED_B = {"time", "curvature_hangoff", "tension_hangoff"}


def load_timeseries(path_or_buffer) -> pd.DataFrame:
    if hasattr(path_or_buffer, "name") and str(path_or_buffer.name).endswith(".parquet"):
        return pd.read_parquet(path_or_buffer)
    if isinstance(path_or_buffer, str) and path_or_buffer.endswith(".parquet"):
        return pd.read_parquet(path_or_buffer)
    return pd.read_csv(path_or_buffer, comment="#")


def validate(df: pd.DataFrame) -> str:
    cols = {c.strip().lower() for c in df.columns}
    df.columns = [c.strip().lower() for c in df.columns]
    if REQUIRED_B.issubset(cols):
        return "cable_response"
    if REQUIRED_A.issubset(cols):
        return "platform_motion"
    raise ValueError(
        "Unrecognized columns. Provide either "
        f"{sorted(REQUIRED_A)} (platform motion) or {sorted(REQUIRED_B)} (cable response).")


def run_ingested(df: pd.DataFrame, family: QuasiStaticFamily | None = None,
                 fatigue_params: FatigueParams | None = None, daf: float = 1.0,
                 hangoff_stick: bool = True, discard_s: float = 0.0) -> IngestResult:
    """Run the fatigue pipeline on ingested high-fidelity data."""
    kind = validate(df)
    family = family or build_quasistatic_family()
    fp = fatigue_params or FatigueParams()
    t = df["time"].to_numpy(float)
    mask = t >= (t[0] + discard_s)
    window_s = float(t[mask][-1] - t[mask][0])

    if kind == "platform_motion":
        surge = df["surge"].to_numpy(float)
        pitch_rad = np.radians(df["pitch"].to_numpy(float))
        sigma, _, _ = region_stress_timeseries(family, "hang_off", surge, pitch_rad,
                                                daf=daf, hangoff_stick=hangoff_stick)
    else:  # cable_response — stress directly from curvature + tension
        c = family.cable
        kappa = df["curvature_hangoff"].to_numpy(float)
        T = df["tension_hangoff"].to_numpy(float)
        r_bend = c.armour_pitch_radius_m if hangoff_stick else c.armour_wire_radius_m
        sigma = c.E_steel_Pa * r_bend * kappa + T / c.armour_area_m2

    fat = rainflow_damage(sigma[mask], window_s, fp)
    return IngestResult(kind=kind, columns=list(df.columns), t=t[mask],
                        stress_Pa=sigma[mask], fatigue=fat)


def write_example_dataset(path: str, family: QuasiStaticFamily | None = None) -> str:
    """Generate the bundled example ingest dataset (a documented synthetic stand-in).

    HONEST LABEL: this is produced by HALYARD's own reduced-order engine and exported in the
    ingest format, so the ingest path is demonstrable without an OpenFAST/OrcaFlex licence.
    Replace it with a genuine high-fidelity export to use engine B for real.
    """
    from physics.simulation import SimConfig, run_simulation
    sim = run_simulation(SimConfig(t_end_s=400, dt_s=0.05, Hs_m=1.0))
    df = pd.DataFrame({"time": sim.t, "surge": sim.surge_m, "pitch": sim.pitch_deg})
    header = ("# HALYARD example ingest dataset (platform motion)\n"
              "# PROVENANCE: synthetic stand-in generated by HALYARD's reduced-order engine,\n"
              "# exported in the ingest format. NOT a high-fidelity OpenFAST/OrcaFlex run.\n"
              "# Replace with a genuine export (columns: time[s], surge[m], pitch[deg]).\n")
    with open(path, "w") as fh:
        fh.write(header)
        df.to_csv(fh, index=False)
    return path
